"""initial schema

Revision ID: 134df7431e02
Revises: 
Create Date: 2026-02-18 14:00:26.007873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '134df7431e02'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inventory_history_id'), table_name='inventory_history')
    op.add_column('products', sa.Column('source_system', sa.String(length=50), nullable=True))
    op.alter_column('products', 'sku',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('products', 'last_updated',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'last_updated',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('products', 'sku',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_column('products', 'source_system')
    op.create_index(op.f('ix_inventory_history_id'), 'inventory_history', ['id'], unique=False)
    # ### end Alembic commands ###
