"""sync schema

Revision ID: c355bc30f1d6
Revises: 
Create Date: 2026-02-17 11:47:23.322381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c355bc30f1d6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inventory_history_id'), table_name='inventory_history')
    op.add_column('products', sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('products', sa.Column('source_system', sa.String(length=50), nullable=False))
    op.alter_column('products', 'sku',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_index(op.f('ix_products_barcode'), table_name='products')
    op.drop_index(op.f('ix_products_is_low_stock'), table_name='products')
    op.drop_column('products', 'barcode')
    op.drop_column('products', 'is_low_stock')
    op.drop_column('products', 'min_quantity')
    op.drop_column('products', 'reorder_point')
    op.drop_column('products', 'updated_at')
    op.drop_column('products', 'max_quantity')
    op.drop_column('products', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('max_quantity', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('reorder_point', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('min_quantity', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('is_low_stock', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('barcode', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_products_is_low_stock'), 'products', ['is_low_stock'], unique=False)
    op.create_index(op.f('ix_products_barcode'), 'products', ['barcode'], unique=True)
    op.alter_column('products', 'sku',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_column('products', 'source_system')
    op.drop_column('products', 'last_updated')
    op.create_index(op.f('ix_inventory_history_id'), 'inventory_history', ['id'], unique=False)
    # ### end Alembic commands ###
